// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Struct.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_Struct_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_Struct_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "Enum.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_Struct_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_Struct_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_Struct_2eproto;
namespace Protocol {
class AxialCoord;
struct AxialCoordDefaultTypeInternal;
extern AxialCoordDefaultTypeInternal _AxialCoord_default_instance_;
class BattleActionLog;
struct BattleActionLogDefaultTypeInternal;
extern BattleActionLogDefaultTypeInternal _BattleActionLog_default_instance_;
class BattlePawnDelta;
struct BattlePawnDeltaDefaultTypeInternal;
extern BattlePawnDeltaDefaultTypeInternal _BattlePawnDelta_default_instance_;
class BattlePawnInfo;
struct BattlePawnInfoDefaultTypeInternal;
extern BattlePawnInfoDefaultTypeInternal _BattlePawnInfo_default_instance_;
class ObjectInfo;
struct ObjectInfoDefaultTypeInternal;
extern ObjectInfoDefaultTypeInternal _ObjectInfo_default_instance_;
class Vec2Fixed;
struct Vec2FixedDefaultTypeInternal;
extern Vec2FixedDefaultTypeInternal _Vec2Fixed_default_instance_;
}  // namespace Protocol
PROTOBUF_NAMESPACE_OPEN
template<> ::Protocol::AxialCoord* Arena::CreateMaybeMessage<::Protocol::AxialCoord>(Arena*);
template<> ::Protocol::BattleActionLog* Arena::CreateMaybeMessage<::Protocol::BattleActionLog>(Arena*);
template<> ::Protocol::BattlePawnDelta* Arena::CreateMaybeMessage<::Protocol::BattlePawnDelta>(Arena*);
template<> ::Protocol::BattlePawnInfo* Arena::CreateMaybeMessage<::Protocol::BattlePawnInfo>(Arena*);
template<> ::Protocol::ObjectInfo* Arena::CreateMaybeMessage<::Protocol::ObjectInfo>(Arena*);
template<> ::Protocol::Vec2Fixed* Arena::CreateMaybeMessage<::Protocol::Vec2Fixed>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace Protocol {

// ===================================================================

class Vec2Fixed final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.Vec2Fixed) */ {
 public:
  inline Vec2Fixed() : Vec2Fixed(nullptr) {}
  ~Vec2Fixed() override;
  explicit PROTOBUF_CONSTEXPR Vec2Fixed(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Vec2Fixed(const Vec2Fixed& from);
  Vec2Fixed(Vec2Fixed&& from) noexcept
    : Vec2Fixed() {
    *this = ::std::move(from);
  }

  inline Vec2Fixed& operator=(const Vec2Fixed& from) {
    CopyFrom(from);
    return *this;
  }
  inline Vec2Fixed& operator=(Vec2Fixed&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Vec2Fixed& default_instance() {
    return *internal_default_instance();
  }
  static inline const Vec2Fixed* internal_default_instance() {
    return reinterpret_cast<const Vec2Fixed*>(
               &_Vec2Fixed_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Vec2Fixed& a, Vec2Fixed& b) {
    a.Swap(&b);
  }
  inline void Swap(Vec2Fixed* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Vec2Fixed* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Vec2Fixed* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Vec2Fixed>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Vec2Fixed& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Vec2Fixed& from) {
    Vec2Fixed::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Vec2Fixed* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.Vec2Fixed";
  }
  protected:
  explicit Vec2Fixed(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kXFieldNumber = 1,
    kYFieldNumber = 2,
  };
  // sint32 x = 1;
  void clear_x();
  int32_t x() const;
  void set_x(int32_t value);
  private:
  int32_t _internal_x() const;
  void _internal_set_x(int32_t value);
  public:

  // sint32 y = 2;
  void clear_y();
  int32_t y() const;
  void set_y(int32_t value);
  private:
  int32_t _internal_y() const;
  void _internal_set_y(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.Vec2Fixed)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int32_t x_;
    int32_t y_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Struct_2eproto;
};
// -------------------------------------------------------------------

class AxialCoord final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.AxialCoord) */ {
 public:
  inline AxialCoord() : AxialCoord(nullptr) {}
  ~AxialCoord() override;
  explicit PROTOBUF_CONSTEXPR AxialCoord(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  AxialCoord(const AxialCoord& from);
  AxialCoord(AxialCoord&& from) noexcept
    : AxialCoord() {
    *this = ::std::move(from);
  }

  inline AxialCoord& operator=(const AxialCoord& from) {
    CopyFrom(from);
    return *this;
  }
  inline AxialCoord& operator=(AxialCoord&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const AxialCoord& default_instance() {
    return *internal_default_instance();
  }
  static inline const AxialCoord* internal_default_instance() {
    return reinterpret_cast<const AxialCoord*>(
               &_AxialCoord_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(AxialCoord& a, AxialCoord& b) {
    a.Swap(&b);
  }
  inline void Swap(AxialCoord* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AxialCoord* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  AxialCoord* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<AxialCoord>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const AxialCoord& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const AxialCoord& from) {
    AxialCoord::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(AxialCoord* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.AxialCoord";
  }
  protected:
  explicit AxialCoord(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kQFieldNumber = 1,
    kRFieldNumber = 2,
  };
  // sint32 q = 1;
  void clear_q();
  int32_t q() const;
  void set_q(int32_t value);
  private:
  int32_t _internal_q() const;
  void _internal_set_q(int32_t value);
  public:

  // sint32 r = 2;
  void clear_r();
  int32_t r() const;
  void set_r(int32_t value);
  private:
  int32_t _internal_r() const;
  void _internal_set_r(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.AxialCoord)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int32_t q_;
    int32_t r_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Struct_2eproto;
};
// -------------------------------------------------------------------

class ObjectInfo final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.ObjectInfo) */ {
 public:
  inline ObjectInfo() : ObjectInfo(nullptr) {}
  ~ObjectInfo() override;
  explicit PROTOBUF_CONSTEXPR ObjectInfo(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ObjectInfo(const ObjectInfo& from);
  ObjectInfo(ObjectInfo&& from) noexcept
    : ObjectInfo() {
    *this = ::std::move(from);
  }

  inline ObjectInfo& operator=(const ObjectInfo& from) {
    CopyFrom(from);
    return *this;
  }
  inline ObjectInfo& operator=(ObjectInfo&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ObjectInfo& default_instance() {
    return *internal_default_instance();
  }
  static inline const ObjectInfo* internal_default_instance() {
    return reinterpret_cast<const ObjectInfo*>(
               &_ObjectInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(ObjectInfo& a, ObjectInfo& b) {
    a.Swap(&b);
  }
  inline void Swap(ObjectInfo* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ObjectInfo* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ObjectInfo* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ObjectInfo>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ObjectInfo& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const ObjectInfo& from) {
    ObjectInfo::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ObjectInfo* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.ObjectInfo";
  }
  protected:
  explicit ObjectInfo(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPositionFieldNumber = 4,
    kObjectIdFieldNumber = 1,
    kObjectTypeFieldNumber = 2,
    kCreatureTypeFieldNumber = 3,
  };
  // .Protocol.Vec2Fixed position = 4;
  bool has_position() const;
  private:
  bool _internal_has_position() const;
  public:
  void clear_position();
  const ::Protocol::Vec2Fixed& position() const;
  PROTOBUF_NODISCARD ::Protocol::Vec2Fixed* release_position();
  ::Protocol::Vec2Fixed* mutable_position();
  void set_allocated_position(::Protocol::Vec2Fixed* position);
  private:
  const ::Protocol::Vec2Fixed& _internal_position() const;
  ::Protocol::Vec2Fixed* _internal_mutable_position();
  public:
  void unsafe_arena_set_allocated_position(
      ::Protocol::Vec2Fixed* position);
  ::Protocol::Vec2Fixed* unsafe_arena_release_position();

  // uint64 object_id = 1;
  void clear_object_id();
  uint64_t object_id() const;
  void set_object_id(uint64_t value);
  private:
  uint64_t _internal_object_id() const;
  void _internal_set_object_id(uint64_t value);
  public:

  // .Protocol.ObjectType object_type = 2;
  void clear_object_type();
  ::Protocol::ObjectType object_type() const;
  void set_object_type(::Protocol::ObjectType value);
  private:
  ::Protocol::ObjectType _internal_object_type() const;
  void _internal_set_object_type(::Protocol::ObjectType value);
  public:

  // .Protocol.CreatureType creature_type = 3;
  void clear_creature_type();
  ::Protocol::CreatureType creature_type() const;
  void set_creature_type(::Protocol::CreatureType value);
  private:
  ::Protocol::CreatureType _internal_creature_type() const;
  void _internal_set_creature_type(::Protocol::CreatureType value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.ObjectInfo)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::Protocol::Vec2Fixed* position_;
    uint64_t object_id_;
    int object_type_;
    int creature_type_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Struct_2eproto;
};
// -------------------------------------------------------------------

class BattlePawnInfo final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.BattlePawnInfo) */ {
 public:
  inline BattlePawnInfo() : BattlePawnInfo(nullptr) {}
  ~BattlePawnInfo() override;
  explicit PROTOBUF_CONSTEXPR BattlePawnInfo(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  BattlePawnInfo(const BattlePawnInfo& from);
  BattlePawnInfo(BattlePawnInfo&& from) noexcept
    : BattlePawnInfo() {
    *this = ::std::move(from);
  }

  inline BattlePawnInfo& operator=(const BattlePawnInfo& from) {
    CopyFrom(from);
    return *this;
  }
  inline BattlePawnInfo& operator=(BattlePawnInfo&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const BattlePawnInfo& default_instance() {
    return *internal_default_instance();
  }
  static inline const BattlePawnInfo* internal_default_instance() {
    return reinterpret_cast<const BattlePawnInfo*>(
               &_BattlePawnInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(BattlePawnInfo& a, BattlePawnInfo& b) {
    a.Swap(&b);
  }
  inline void Swap(BattlePawnInfo* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(BattlePawnInfo* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  BattlePawnInfo* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<BattlePawnInfo>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const BattlePawnInfo& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const BattlePawnInfo& from) {
    BattlePawnInfo::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(BattlePawnInfo* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.BattlePawnInfo";
  }
  protected:
  explicit BattlePawnInfo(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kAxialFieldNumber = 4,
    kPawnIdFieldNumber = 1,
    kOwnerIdFieldNumber = 2,
    kPawnClassFieldNumber = 3,
    kHpFieldNumber = 5,
    kMaxHpFieldNumber = 6,
    kMoveRangeFieldNumber = 7,
    kArmorFieldNumber = 8,
    kMaxArmorFieldNumber = 9,
    kCurrentApFieldNumber = 10,
    kCanMoveFieldNumber = 11,
    kUsedSubActionThisTurnFieldNumber = 12,
    kUsedUltimateFieldNumber = 13,
    kIsShieldUnitFieldNumber = 14,
    kIsMeleeFieldNumber = 15,
  };
  // .Protocol.AxialCoord axial = 4;
  bool has_axial() const;
  private:
  bool _internal_has_axial() const;
  public:
  void clear_axial();
  const ::Protocol::AxialCoord& axial() const;
  PROTOBUF_NODISCARD ::Protocol::AxialCoord* release_axial();
  ::Protocol::AxialCoord* mutable_axial();
  void set_allocated_axial(::Protocol::AxialCoord* axial);
  private:
  const ::Protocol::AxialCoord& _internal_axial() const;
  ::Protocol::AxialCoord* _internal_mutable_axial();
  public:
  void unsafe_arena_set_allocated_axial(
      ::Protocol::AxialCoord* axial);
  ::Protocol::AxialCoord* unsafe_arena_release_axial();

  // uint64 pawn_id = 1;
  void clear_pawn_id();
  uint64_t pawn_id() const;
  void set_pawn_id(uint64_t value);
  private:
  uint64_t _internal_pawn_id() const;
  void _internal_set_pawn_id(uint64_t value);
  public:

  // uint64 owner_id = 2;
  void clear_owner_id();
  uint64_t owner_id() const;
  void set_owner_id(uint64_t value);
  private:
  uint64_t _internal_owner_id() const;
  void _internal_set_owner_id(uint64_t value);
  public:

  // .Protocol.PawnClass pawn_class = 3;
  void clear_pawn_class();
  ::Protocol::PawnClass pawn_class() const;
  void set_pawn_class(::Protocol::PawnClass value);
  private:
  ::Protocol::PawnClass _internal_pawn_class() const;
  void _internal_set_pawn_class(::Protocol::PawnClass value);
  public:

  // int32 hp = 5;
  void clear_hp();
  int32_t hp() const;
  void set_hp(int32_t value);
  private:
  int32_t _internal_hp() const;
  void _internal_set_hp(int32_t value);
  public:

  // int32 max_hp = 6;
  void clear_max_hp();
  int32_t max_hp() const;
  void set_max_hp(int32_t value);
  private:
  int32_t _internal_max_hp() const;
  void _internal_set_max_hp(int32_t value);
  public:

  // int32 move_range = 7;
  void clear_move_range();
  int32_t move_range() const;
  void set_move_range(int32_t value);
  private:
  int32_t _internal_move_range() const;
  void _internal_set_move_range(int32_t value);
  public:

  // int32 armor = 8;
  void clear_armor();
  int32_t armor() const;
  void set_armor(int32_t value);
  private:
  int32_t _internal_armor() const;
  void _internal_set_armor(int32_t value);
  public:

  // int32 max_armor = 9;
  void clear_max_armor();
  int32_t max_armor() const;
  void set_max_armor(int32_t value);
  private:
  int32_t _internal_max_armor() const;
  void _internal_set_max_armor(int32_t value);
  public:

  // int32 current_ap = 10;
  void clear_current_ap();
  int32_t current_ap() const;
  void set_current_ap(int32_t value);
  private:
  int32_t _internal_current_ap() const;
  void _internal_set_current_ap(int32_t value);
  public:

  // bool can_move = 11;
  void clear_can_move();
  bool can_move() const;
  void set_can_move(bool value);
  private:
  bool _internal_can_move() const;
  void _internal_set_can_move(bool value);
  public:

  // bool used_sub_action_this_turn = 12;
  void clear_used_sub_action_this_turn();
  bool used_sub_action_this_turn() const;
  void set_used_sub_action_this_turn(bool value);
  private:
  bool _internal_used_sub_action_this_turn() const;
  void _internal_set_used_sub_action_this_turn(bool value);
  public:

  // bool used_ultimate = 13;
  void clear_used_ultimate();
  bool used_ultimate() const;
  void set_used_ultimate(bool value);
  private:
  bool _internal_used_ultimate() const;
  void _internal_set_used_ultimate(bool value);
  public:

  // bool is_shield_unit = 14;
  void clear_is_shield_unit();
  bool is_shield_unit() const;
  void set_is_shield_unit(bool value);
  private:
  bool _internal_is_shield_unit() const;
  void _internal_set_is_shield_unit(bool value);
  public:

  // bool is_melee = 15;
  void clear_is_melee();
  bool is_melee() const;
  void set_is_melee(bool value);
  private:
  bool _internal_is_melee() const;
  void _internal_set_is_melee(bool value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.BattlePawnInfo)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::Protocol::AxialCoord* axial_;
    uint64_t pawn_id_;
    uint64_t owner_id_;
    int pawn_class_;
    int32_t hp_;
    int32_t max_hp_;
    int32_t move_range_;
    int32_t armor_;
    int32_t max_armor_;
    int32_t current_ap_;
    bool can_move_;
    bool used_sub_action_this_turn_;
    bool used_ultimate_;
    bool is_shield_unit_;
    bool is_melee_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Struct_2eproto;
};
// -------------------------------------------------------------------

class BattlePawnDelta final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.BattlePawnDelta) */ {
 public:
  inline BattlePawnDelta() : BattlePawnDelta(nullptr) {}
  ~BattlePawnDelta() override;
  explicit PROTOBUF_CONSTEXPR BattlePawnDelta(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  BattlePawnDelta(const BattlePawnDelta& from);
  BattlePawnDelta(BattlePawnDelta&& from) noexcept
    : BattlePawnDelta() {
    *this = ::std::move(from);
  }

  inline BattlePawnDelta& operator=(const BattlePawnDelta& from) {
    CopyFrom(from);
    return *this;
  }
  inline BattlePawnDelta& operator=(BattlePawnDelta&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const BattlePawnDelta& default_instance() {
    return *internal_default_instance();
  }
  static inline const BattlePawnDelta* internal_default_instance() {
    return reinterpret_cast<const BattlePawnDelta*>(
               &_BattlePawnDelta_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(BattlePawnDelta& a, BattlePawnDelta& b) {
    a.Swap(&b);
  }
  inline void Swap(BattlePawnDelta* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(BattlePawnDelta* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  BattlePawnDelta* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<BattlePawnDelta>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const BattlePawnDelta& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const BattlePawnDelta& from) {
    BattlePawnDelta::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(BattlePawnDelta* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.BattlePawnDelta";
  }
  protected:
  explicit BattlePawnDelta(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPawnIdFieldNumber = 1,
    kHpFieldNumber = 2,
    kArmorFieldNumber = 3,
    kCurrentApFieldNumber = 4,
    kCanMoveFieldNumber = 5,
    kUsedSubActionThisTurnFieldNumber = 6,
    kUsedUltimateFieldNumber = 7,
  };
  // uint64 pawn_id = 1;
  void clear_pawn_id();
  uint64_t pawn_id() const;
  void set_pawn_id(uint64_t value);
  private:
  uint64_t _internal_pawn_id() const;
  void _internal_set_pawn_id(uint64_t value);
  public:

  // int32 hp = 2;
  void clear_hp();
  int32_t hp() const;
  void set_hp(int32_t value);
  private:
  int32_t _internal_hp() const;
  void _internal_set_hp(int32_t value);
  public:

  // int32 armor = 3;
  void clear_armor();
  int32_t armor() const;
  void set_armor(int32_t value);
  private:
  int32_t _internal_armor() const;
  void _internal_set_armor(int32_t value);
  public:

  // int32 current_ap = 4;
  void clear_current_ap();
  int32_t current_ap() const;
  void set_current_ap(int32_t value);
  private:
  int32_t _internal_current_ap() const;
  void _internal_set_current_ap(int32_t value);
  public:

  // bool can_move = 5;
  void clear_can_move();
  bool can_move() const;
  void set_can_move(bool value);
  private:
  bool _internal_can_move() const;
  void _internal_set_can_move(bool value);
  public:

  // bool used_sub_action_this_turn = 6;
  void clear_used_sub_action_this_turn();
  bool used_sub_action_this_turn() const;
  void set_used_sub_action_this_turn(bool value);
  private:
  bool _internal_used_sub_action_this_turn() const;
  void _internal_set_used_sub_action_this_turn(bool value);
  public:

  // bool used_ultimate = 7;
  void clear_used_ultimate();
  bool used_ultimate() const;
  void set_used_ultimate(bool value);
  private:
  bool _internal_used_ultimate() const;
  void _internal_set_used_ultimate(bool value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.BattlePawnDelta)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    uint64_t pawn_id_;
    int32_t hp_;
    int32_t armor_;
    int32_t current_ap_;
    bool can_move_;
    bool used_sub_action_this_turn_;
    bool used_ultimate_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Struct_2eproto;
};
// -------------------------------------------------------------------

class BattleActionLog final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.BattleActionLog) */ {
 public:
  inline BattleActionLog() : BattleActionLog(nullptr) {}
  ~BattleActionLog() override;
  explicit PROTOBUF_CONSTEXPR BattleActionLog(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  BattleActionLog(const BattleActionLog& from);
  BattleActionLog(BattleActionLog&& from) noexcept
    : BattleActionLog() {
    *this = ::std::move(from);
  }

  inline BattleActionLog& operator=(const BattleActionLog& from) {
    CopyFrom(from);
    return *this;
  }
  inline BattleActionLog& operator=(BattleActionLog&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const BattleActionLog& default_instance() {
    return *internal_default_instance();
  }
  static inline const BattleActionLog* internal_default_instance() {
    return reinterpret_cast<const BattleActionLog*>(
               &_BattleActionLog_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  friend void swap(BattleActionLog& a, BattleActionLog& b) {
    a.Swap(&b);
  }
  inline void Swap(BattleActionLog* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(BattleActionLog* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  BattleActionLog* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<BattleActionLog>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const BattleActionLog& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const BattleActionLog& from) {
    BattleActionLog::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(BattleActionLog* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.BattleActionLog";
  }
  protected:
  explicit BattleActionLog(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kActionTypeFieldNumber = 4,
    kAttackerPawnIdFieldNumber = 1,
    kDefenderPawnIdFieldNumber = 2,
    kSkillSlotFieldNumber = 3,
    kDamageFieldNumber = 5,
    kIsCriticalFieldNumber = 6,
    kIsEvadedFieldNumber = 7,
    kIsGuardedFieldNumber = 8,
    kIsPerfectGuardedFieldNumber = 9,
    kIsCounterFieldNumber = 10,
    kHpAfterFieldNumber = 11,
    kArmorAfterFieldNumber = 12,
  };
  // string action_type = 4;
  void clear_action_type();
  const std::string& action_type() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_action_type(ArgT0&& arg0, ArgT... args);
  std::string* mutable_action_type();
  PROTOBUF_NODISCARD std::string* release_action_type();
  void set_allocated_action_type(std::string* action_type);
  private:
  const std::string& _internal_action_type() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_action_type(const std::string& value);
  std::string* _internal_mutable_action_type();
  public:

  // uint64 attacker_pawn_id = 1;
  void clear_attacker_pawn_id();
  uint64_t attacker_pawn_id() const;
  void set_attacker_pawn_id(uint64_t value);
  private:
  uint64_t _internal_attacker_pawn_id() const;
  void _internal_set_attacker_pawn_id(uint64_t value);
  public:

  // uint64 defender_pawn_id = 2;
  void clear_defender_pawn_id();
  uint64_t defender_pawn_id() const;
  void set_defender_pawn_id(uint64_t value);
  private:
  uint64_t _internal_defender_pawn_id() const;
  void _internal_set_defender_pawn_id(uint64_t value);
  public:

  // int32 skill_slot = 3;
  void clear_skill_slot();
  int32_t skill_slot() const;
  void set_skill_slot(int32_t value);
  private:
  int32_t _internal_skill_slot() const;
  void _internal_set_skill_slot(int32_t value);
  public:

  // int32 damage = 5;
  void clear_damage();
  int32_t damage() const;
  void set_damage(int32_t value);
  private:
  int32_t _internal_damage() const;
  void _internal_set_damage(int32_t value);
  public:

  // bool is_critical = 6;
  void clear_is_critical();
  bool is_critical() const;
  void set_is_critical(bool value);
  private:
  bool _internal_is_critical() const;
  void _internal_set_is_critical(bool value);
  public:

  // bool is_evaded = 7;
  void clear_is_evaded();
  bool is_evaded() const;
  void set_is_evaded(bool value);
  private:
  bool _internal_is_evaded() const;
  void _internal_set_is_evaded(bool value);
  public:

  // bool is_guarded = 8;
  void clear_is_guarded();
  bool is_guarded() const;
  void set_is_guarded(bool value);
  private:
  bool _internal_is_guarded() const;
  void _internal_set_is_guarded(bool value);
  public:

  // bool is_perfect_guarded = 9;
  void clear_is_perfect_guarded();
  bool is_perfect_guarded() const;
  void set_is_perfect_guarded(bool value);
  private:
  bool _internal_is_perfect_guarded() const;
  void _internal_set_is_perfect_guarded(bool value);
  public:

  // bool is_counter = 10;
  void clear_is_counter();
  bool is_counter() const;
  void set_is_counter(bool value);
  private:
  bool _internal_is_counter() const;
  void _internal_set_is_counter(bool value);
  public:

  // int32 hp_after = 11;
  void clear_hp_after();
  int32_t hp_after() const;
  void set_hp_after(int32_t value);
  private:
  int32_t _internal_hp_after() const;
  void _internal_set_hp_after(int32_t value);
  public:

  // int32 armor_after = 12;
  void clear_armor_after();
  int32_t armor_after() const;
  void set_armor_after(int32_t value);
  private:
  int32_t _internal_armor_after() const;
  void _internal_set_armor_after(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.BattleActionLog)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr action_type_;
    uint64_t attacker_pawn_id_;
    uint64_t defender_pawn_id_;
    int32_t skill_slot_;
    int32_t damage_;
    bool is_critical_;
    bool is_evaded_;
    bool is_guarded_;
    bool is_perfect_guarded_;
    bool is_counter_;
    int32_t hp_after_;
    int32_t armor_after_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Struct_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Vec2Fixed

// sint32 x = 1;
inline void Vec2Fixed::clear_x() {
  _impl_.x_ = 0;
}
inline int32_t Vec2Fixed::_internal_x() const {
  return _impl_.x_;
}
inline int32_t Vec2Fixed::x() const {
  // @@protoc_insertion_point(field_get:Protocol.Vec2Fixed.x)
  return _internal_x();
}
inline void Vec2Fixed::_internal_set_x(int32_t value) {
  
  _impl_.x_ = value;
}
inline void Vec2Fixed::set_x(int32_t value) {
  _internal_set_x(value);
  // @@protoc_insertion_point(field_set:Protocol.Vec2Fixed.x)
}

// sint32 y = 2;
inline void Vec2Fixed::clear_y() {
  _impl_.y_ = 0;
}
inline int32_t Vec2Fixed::_internal_y() const {
  return _impl_.y_;
}
inline int32_t Vec2Fixed::y() const {
  // @@protoc_insertion_point(field_get:Protocol.Vec2Fixed.y)
  return _internal_y();
}
inline void Vec2Fixed::_internal_set_y(int32_t value) {
  
  _impl_.y_ = value;
}
inline void Vec2Fixed::set_y(int32_t value) {
  _internal_set_y(value);
  // @@protoc_insertion_point(field_set:Protocol.Vec2Fixed.y)
}

// -------------------------------------------------------------------

// AxialCoord

// sint32 q = 1;
inline void AxialCoord::clear_q() {
  _impl_.q_ = 0;
}
inline int32_t AxialCoord::_internal_q() const {
  return _impl_.q_;
}
inline int32_t AxialCoord::q() const {
  // @@protoc_insertion_point(field_get:Protocol.AxialCoord.q)
  return _internal_q();
}
inline void AxialCoord::_internal_set_q(int32_t value) {
  
  _impl_.q_ = value;
}
inline void AxialCoord::set_q(int32_t value) {
  _internal_set_q(value);
  // @@protoc_insertion_point(field_set:Protocol.AxialCoord.q)
}

// sint32 r = 2;
inline void AxialCoord::clear_r() {
  _impl_.r_ = 0;
}
inline int32_t AxialCoord::_internal_r() const {
  return _impl_.r_;
}
inline int32_t AxialCoord::r() const {
  // @@protoc_insertion_point(field_get:Protocol.AxialCoord.r)
  return _internal_r();
}
inline void AxialCoord::_internal_set_r(int32_t value) {
  
  _impl_.r_ = value;
}
inline void AxialCoord::set_r(int32_t value) {
  _internal_set_r(value);
  // @@protoc_insertion_point(field_set:Protocol.AxialCoord.r)
}

// -------------------------------------------------------------------

// ObjectInfo

// uint64 object_id = 1;
inline void ObjectInfo::clear_object_id() {
  _impl_.object_id_ = uint64_t{0u};
}
inline uint64_t ObjectInfo::_internal_object_id() const {
  return _impl_.object_id_;
}
inline uint64_t ObjectInfo::object_id() const {
  // @@protoc_insertion_point(field_get:Protocol.ObjectInfo.object_id)
  return _internal_object_id();
}
inline void ObjectInfo::_internal_set_object_id(uint64_t value) {
  
  _impl_.object_id_ = value;
}
inline void ObjectInfo::set_object_id(uint64_t value) {
  _internal_set_object_id(value);
  // @@protoc_insertion_point(field_set:Protocol.ObjectInfo.object_id)
}

// .Protocol.ObjectType object_type = 2;
inline void ObjectInfo::clear_object_type() {
  _impl_.object_type_ = 0;
}
inline ::Protocol::ObjectType ObjectInfo::_internal_object_type() const {
  return static_cast< ::Protocol::ObjectType >(_impl_.object_type_);
}
inline ::Protocol::ObjectType ObjectInfo::object_type() const {
  // @@protoc_insertion_point(field_get:Protocol.ObjectInfo.object_type)
  return _internal_object_type();
}
inline void ObjectInfo::_internal_set_object_type(::Protocol::ObjectType value) {
  
  _impl_.object_type_ = value;
}
inline void ObjectInfo::set_object_type(::Protocol::ObjectType value) {
  _internal_set_object_type(value);
  // @@protoc_insertion_point(field_set:Protocol.ObjectInfo.object_type)
}

// .Protocol.CreatureType creature_type = 3;
inline void ObjectInfo::clear_creature_type() {
  _impl_.creature_type_ = 0;
}
inline ::Protocol::CreatureType ObjectInfo::_internal_creature_type() const {
  return static_cast< ::Protocol::CreatureType >(_impl_.creature_type_);
}
inline ::Protocol::CreatureType ObjectInfo::creature_type() const {
  // @@protoc_insertion_point(field_get:Protocol.ObjectInfo.creature_type)
  return _internal_creature_type();
}
inline void ObjectInfo::_internal_set_creature_type(::Protocol::CreatureType value) {
  
  _impl_.creature_type_ = value;
}
inline void ObjectInfo::set_creature_type(::Protocol::CreatureType value) {
  _internal_set_creature_type(value);
  // @@protoc_insertion_point(field_set:Protocol.ObjectInfo.creature_type)
}

// .Protocol.Vec2Fixed position = 4;
inline bool ObjectInfo::_internal_has_position() const {
  return this != internal_default_instance() && _impl_.position_ != nullptr;
}
inline bool ObjectInfo::has_position() const {
  return _internal_has_position();
}
inline void ObjectInfo::clear_position() {
  if (GetArenaForAllocation() == nullptr && _impl_.position_ != nullptr) {
    delete _impl_.position_;
  }
  _impl_.position_ = nullptr;
}
inline const ::Protocol::Vec2Fixed& ObjectInfo::_internal_position() const {
  const ::Protocol::Vec2Fixed* p = _impl_.position_;
  return p != nullptr ? *p : reinterpret_cast<const ::Protocol::Vec2Fixed&>(
      ::Protocol::_Vec2Fixed_default_instance_);
}
inline const ::Protocol::Vec2Fixed& ObjectInfo::position() const {
  // @@protoc_insertion_point(field_get:Protocol.ObjectInfo.position)
  return _internal_position();
}
inline void ObjectInfo::unsafe_arena_set_allocated_position(
    ::Protocol::Vec2Fixed* position) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.position_);
  }
  _impl_.position_ = position;
  if (position) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Protocol.ObjectInfo.position)
}
inline ::Protocol::Vec2Fixed* ObjectInfo::release_position() {
  
  ::Protocol::Vec2Fixed* temp = _impl_.position_;
  _impl_.position_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::Protocol::Vec2Fixed* ObjectInfo::unsafe_arena_release_position() {
  // @@protoc_insertion_point(field_release:Protocol.ObjectInfo.position)
  
  ::Protocol::Vec2Fixed* temp = _impl_.position_;
  _impl_.position_ = nullptr;
  return temp;
}
inline ::Protocol::Vec2Fixed* ObjectInfo::_internal_mutable_position() {
  
  if (_impl_.position_ == nullptr) {
    auto* p = CreateMaybeMessage<::Protocol::Vec2Fixed>(GetArenaForAllocation());
    _impl_.position_ = p;
  }
  return _impl_.position_;
}
inline ::Protocol::Vec2Fixed* ObjectInfo::mutable_position() {
  ::Protocol::Vec2Fixed* _msg = _internal_mutable_position();
  // @@protoc_insertion_point(field_mutable:Protocol.ObjectInfo.position)
  return _msg;
}
inline void ObjectInfo::set_allocated_position(::Protocol::Vec2Fixed* position) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.position_;
  }
  if (position) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(position);
    if (message_arena != submessage_arena) {
      position = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, position, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.position_ = position;
  // @@protoc_insertion_point(field_set_allocated:Protocol.ObjectInfo.position)
}

// -------------------------------------------------------------------

// BattlePawnInfo

// uint64 pawn_id = 1;
inline void BattlePawnInfo::clear_pawn_id() {
  _impl_.pawn_id_ = uint64_t{0u};
}
inline uint64_t BattlePawnInfo::_internal_pawn_id() const {
  return _impl_.pawn_id_;
}
inline uint64_t BattlePawnInfo::pawn_id() const {
  // @@protoc_insertion_point(field_get:Protocol.BattlePawnInfo.pawn_id)
  return _internal_pawn_id();
}
inline void BattlePawnInfo::_internal_set_pawn_id(uint64_t value) {
  
  _impl_.pawn_id_ = value;
}
inline void BattlePawnInfo::set_pawn_id(uint64_t value) {
  _internal_set_pawn_id(value);
  // @@protoc_insertion_point(field_set:Protocol.BattlePawnInfo.pawn_id)
}

// uint64 owner_id = 2;
inline void BattlePawnInfo::clear_owner_id() {
  _impl_.owner_id_ = uint64_t{0u};
}
inline uint64_t BattlePawnInfo::_internal_owner_id() const {
  return _impl_.owner_id_;
}
inline uint64_t BattlePawnInfo::owner_id() const {
  // @@protoc_insertion_point(field_get:Protocol.BattlePawnInfo.owner_id)
  return _internal_owner_id();
}
inline void BattlePawnInfo::_internal_set_owner_id(uint64_t value) {
  
  _impl_.owner_id_ = value;
}
inline void BattlePawnInfo::set_owner_id(uint64_t value) {
  _internal_set_owner_id(value);
  // @@protoc_insertion_point(field_set:Protocol.BattlePawnInfo.owner_id)
}

// .Protocol.PawnClass pawn_class = 3;
inline void BattlePawnInfo::clear_pawn_class() {
  _impl_.pawn_class_ = 0;
}
inline ::Protocol::PawnClass BattlePawnInfo::_internal_pawn_class() const {
  return static_cast< ::Protocol::PawnClass >(_impl_.pawn_class_);
}
inline ::Protocol::PawnClass BattlePawnInfo::pawn_class() const {
  // @@protoc_insertion_point(field_get:Protocol.BattlePawnInfo.pawn_class)
  return _internal_pawn_class();
}
inline void BattlePawnInfo::_internal_set_pawn_class(::Protocol::PawnClass value) {
  
  _impl_.pawn_class_ = value;
}
inline void BattlePawnInfo::set_pawn_class(::Protocol::PawnClass value) {
  _internal_set_pawn_class(value);
  // @@protoc_insertion_point(field_set:Protocol.BattlePawnInfo.pawn_class)
}

// .Protocol.AxialCoord axial = 4;
inline bool BattlePawnInfo::_internal_has_axial() const {
  return this != internal_default_instance() && _impl_.axial_ != nullptr;
}
inline bool BattlePawnInfo::has_axial() const {
  return _internal_has_axial();
}
inline void BattlePawnInfo::clear_axial() {
  if (GetArenaForAllocation() == nullptr && _impl_.axial_ != nullptr) {
    delete _impl_.axial_;
  }
  _impl_.axial_ = nullptr;
}
inline const ::Protocol::AxialCoord& BattlePawnInfo::_internal_axial() const {
  const ::Protocol::AxialCoord* p = _impl_.axial_;
  return p != nullptr ? *p : reinterpret_cast<const ::Protocol::AxialCoord&>(
      ::Protocol::_AxialCoord_default_instance_);
}
inline const ::Protocol::AxialCoord& BattlePawnInfo::axial() const {
  // @@protoc_insertion_point(field_get:Protocol.BattlePawnInfo.axial)
  return _internal_axial();
}
inline void BattlePawnInfo::unsafe_arena_set_allocated_axial(
    ::Protocol::AxialCoord* axial) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.axial_);
  }
  _impl_.axial_ = axial;
  if (axial) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Protocol.BattlePawnInfo.axial)
}
inline ::Protocol::AxialCoord* BattlePawnInfo::release_axial() {
  
  ::Protocol::AxialCoord* temp = _impl_.axial_;
  _impl_.axial_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::Protocol::AxialCoord* BattlePawnInfo::unsafe_arena_release_axial() {
  // @@protoc_insertion_point(field_release:Protocol.BattlePawnInfo.axial)
  
  ::Protocol::AxialCoord* temp = _impl_.axial_;
  _impl_.axial_ = nullptr;
  return temp;
}
inline ::Protocol::AxialCoord* BattlePawnInfo::_internal_mutable_axial() {
  
  if (_impl_.axial_ == nullptr) {
    auto* p = CreateMaybeMessage<::Protocol::AxialCoord>(GetArenaForAllocation());
    _impl_.axial_ = p;
  }
  return _impl_.axial_;
}
inline ::Protocol::AxialCoord* BattlePawnInfo::mutable_axial() {
  ::Protocol::AxialCoord* _msg = _internal_mutable_axial();
  // @@protoc_insertion_point(field_mutable:Protocol.BattlePawnInfo.axial)
  return _msg;
}
inline void BattlePawnInfo::set_allocated_axial(::Protocol::AxialCoord* axial) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.axial_;
  }
  if (axial) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(axial);
    if (message_arena != submessage_arena) {
      axial = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, axial, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.axial_ = axial;
  // @@protoc_insertion_point(field_set_allocated:Protocol.BattlePawnInfo.axial)
}

// int32 hp = 5;
inline void BattlePawnInfo::clear_hp() {
  _impl_.hp_ = 0;
}
inline int32_t BattlePawnInfo::_internal_hp() const {
  return _impl_.hp_;
}
inline int32_t BattlePawnInfo::hp() const {
  // @@protoc_insertion_point(field_get:Protocol.BattlePawnInfo.hp)
  return _internal_hp();
}
inline void BattlePawnInfo::_internal_set_hp(int32_t value) {
  
  _impl_.hp_ = value;
}
inline void BattlePawnInfo::set_hp(int32_t value) {
  _internal_set_hp(value);
  // @@protoc_insertion_point(field_set:Protocol.BattlePawnInfo.hp)
}

// int32 max_hp = 6;
inline void BattlePawnInfo::clear_max_hp() {
  _impl_.max_hp_ = 0;
}
inline int32_t BattlePawnInfo::_internal_max_hp() const {
  return _impl_.max_hp_;
}
inline int32_t BattlePawnInfo::max_hp() const {
  // @@protoc_insertion_point(field_get:Protocol.BattlePawnInfo.max_hp)
  return _internal_max_hp();
}
inline void BattlePawnInfo::_internal_set_max_hp(int32_t value) {
  
  _impl_.max_hp_ = value;
}
inline void BattlePawnInfo::set_max_hp(int32_t value) {
  _internal_set_max_hp(value);
  // @@protoc_insertion_point(field_set:Protocol.BattlePawnInfo.max_hp)
}

// int32 move_range = 7;
inline void BattlePawnInfo::clear_move_range() {
  _impl_.move_range_ = 0;
}
inline int32_t BattlePawnInfo::_internal_move_range() const {
  return _impl_.move_range_;
}
inline int32_t BattlePawnInfo::move_range() const {
  // @@protoc_insertion_point(field_get:Protocol.BattlePawnInfo.move_range)
  return _internal_move_range();
}
inline void BattlePawnInfo::_internal_set_move_range(int32_t value) {
  
  _impl_.move_range_ = value;
}
inline void BattlePawnInfo::set_move_range(int32_t value) {
  _internal_set_move_range(value);
  // @@protoc_insertion_point(field_set:Protocol.BattlePawnInfo.move_range)
}

// int32 armor = 8;
inline void BattlePawnInfo::clear_armor() {
  _impl_.armor_ = 0;
}
inline int32_t BattlePawnInfo::_internal_armor() const {
  return _impl_.armor_;
}
inline int32_t BattlePawnInfo::armor() const {
  // @@protoc_insertion_point(field_get:Protocol.BattlePawnInfo.armor)
  return _internal_armor();
}
inline void BattlePawnInfo::_internal_set_armor(int32_t value) {
  
  _impl_.armor_ = value;
}
inline void BattlePawnInfo::set_armor(int32_t value) {
  _internal_set_armor(value);
  // @@protoc_insertion_point(field_set:Protocol.BattlePawnInfo.armor)
}

// int32 max_armor = 9;
inline void BattlePawnInfo::clear_max_armor() {
  _impl_.max_armor_ = 0;
}
inline int32_t BattlePawnInfo::_internal_max_armor() const {
  return _impl_.max_armor_;
}
inline int32_t BattlePawnInfo::max_armor() const {
  // @@protoc_insertion_point(field_get:Protocol.BattlePawnInfo.max_armor)
  return _internal_max_armor();
}
inline void BattlePawnInfo::_internal_set_max_armor(int32_t value) {
  
  _impl_.max_armor_ = value;
}
inline void BattlePawnInfo::set_max_armor(int32_t value) {
  _internal_set_max_armor(value);
  // @@protoc_insertion_point(field_set:Protocol.BattlePawnInfo.max_armor)
}

// int32 current_ap = 10;
inline void BattlePawnInfo::clear_current_ap() {
  _impl_.current_ap_ = 0;
}
inline int32_t BattlePawnInfo::_internal_current_ap() const {
  return _impl_.current_ap_;
}
inline int32_t BattlePawnInfo::current_ap() const {
  // @@protoc_insertion_point(field_get:Protocol.BattlePawnInfo.current_ap)
  return _internal_current_ap();
}
inline void BattlePawnInfo::_internal_set_current_ap(int32_t value) {
  
  _impl_.current_ap_ = value;
}
inline void BattlePawnInfo::set_current_ap(int32_t value) {
  _internal_set_current_ap(value);
  // @@protoc_insertion_point(field_set:Protocol.BattlePawnInfo.current_ap)
}

// bool can_move = 11;
inline void BattlePawnInfo::clear_can_move() {
  _impl_.can_move_ = false;
}
inline bool BattlePawnInfo::_internal_can_move() const {
  return _impl_.can_move_;
}
inline bool BattlePawnInfo::can_move() const {
  // @@protoc_insertion_point(field_get:Protocol.BattlePawnInfo.can_move)
  return _internal_can_move();
}
inline void BattlePawnInfo::_internal_set_can_move(bool value) {
  
  _impl_.can_move_ = value;
}
inline void BattlePawnInfo::set_can_move(bool value) {
  _internal_set_can_move(value);
  // @@protoc_insertion_point(field_set:Protocol.BattlePawnInfo.can_move)
}

// bool used_sub_action_this_turn = 12;
inline void BattlePawnInfo::clear_used_sub_action_this_turn() {
  _impl_.used_sub_action_this_turn_ = false;
}
inline bool BattlePawnInfo::_internal_used_sub_action_this_turn() const {
  return _impl_.used_sub_action_this_turn_;
}
inline bool BattlePawnInfo::used_sub_action_this_turn() const {
  // @@protoc_insertion_point(field_get:Protocol.BattlePawnInfo.used_sub_action_this_turn)
  return _internal_used_sub_action_this_turn();
}
inline void BattlePawnInfo::_internal_set_used_sub_action_this_turn(bool value) {
  
  _impl_.used_sub_action_this_turn_ = value;
}
inline void BattlePawnInfo::set_used_sub_action_this_turn(bool value) {
  _internal_set_used_sub_action_this_turn(value);
  // @@protoc_insertion_point(field_set:Protocol.BattlePawnInfo.used_sub_action_this_turn)
}

// bool used_ultimate = 13;
inline void BattlePawnInfo::clear_used_ultimate() {
  _impl_.used_ultimate_ = false;
}
inline bool BattlePawnInfo::_internal_used_ultimate() const {
  return _impl_.used_ultimate_;
}
inline bool BattlePawnInfo::used_ultimate() const {
  // @@protoc_insertion_point(field_get:Protocol.BattlePawnInfo.used_ultimate)
  return _internal_used_ultimate();
}
inline void BattlePawnInfo::_internal_set_used_ultimate(bool value) {
  
  _impl_.used_ultimate_ = value;
}
inline void BattlePawnInfo::set_used_ultimate(bool value) {
  _internal_set_used_ultimate(value);
  // @@protoc_insertion_point(field_set:Protocol.BattlePawnInfo.used_ultimate)
}

// bool is_shield_unit = 14;
inline void BattlePawnInfo::clear_is_shield_unit() {
  _impl_.is_shield_unit_ = false;
}
inline bool BattlePawnInfo::_internal_is_shield_unit() const {
  return _impl_.is_shield_unit_;
}
inline bool BattlePawnInfo::is_shield_unit() const {
  // @@protoc_insertion_point(field_get:Protocol.BattlePawnInfo.is_shield_unit)
  return _internal_is_shield_unit();
}
inline void BattlePawnInfo::_internal_set_is_shield_unit(bool value) {
  
  _impl_.is_shield_unit_ = value;
}
inline void BattlePawnInfo::set_is_shield_unit(bool value) {
  _internal_set_is_shield_unit(value);
  // @@protoc_insertion_point(field_set:Protocol.BattlePawnInfo.is_shield_unit)
}

// bool is_melee = 15;
inline void BattlePawnInfo::clear_is_melee() {
  _impl_.is_melee_ = false;
}
inline bool BattlePawnInfo::_internal_is_melee() const {
  return _impl_.is_melee_;
}
inline bool BattlePawnInfo::is_melee() const {
  // @@protoc_insertion_point(field_get:Protocol.BattlePawnInfo.is_melee)
  return _internal_is_melee();
}
inline void BattlePawnInfo::_internal_set_is_melee(bool value) {
  
  _impl_.is_melee_ = value;
}
inline void BattlePawnInfo::set_is_melee(bool value) {
  _internal_set_is_melee(value);
  // @@protoc_insertion_point(field_set:Protocol.BattlePawnInfo.is_melee)
}

// -------------------------------------------------------------------

// BattlePawnDelta

// uint64 pawn_id = 1;
inline void BattlePawnDelta::clear_pawn_id() {
  _impl_.pawn_id_ = uint64_t{0u};
}
inline uint64_t BattlePawnDelta::_internal_pawn_id() const {
  return _impl_.pawn_id_;
}
inline uint64_t BattlePawnDelta::pawn_id() const {
  // @@protoc_insertion_point(field_get:Protocol.BattlePawnDelta.pawn_id)
  return _internal_pawn_id();
}
inline void BattlePawnDelta::_internal_set_pawn_id(uint64_t value) {
  
  _impl_.pawn_id_ = value;
}
inline void BattlePawnDelta::set_pawn_id(uint64_t value) {
  _internal_set_pawn_id(value);
  // @@protoc_insertion_point(field_set:Protocol.BattlePawnDelta.pawn_id)
}

// int32 hp = 2;
inline void BattlePawnDelta::clear_hp() {
  _impl_.hp_ = 0;
}
inline int32_t BattlePawnDelta::_internal_hp() const {
  return _impl_.hp_;
}
inline int32_t BattlePawnDelta::hp() const {
  // @@protoc_insertion_point(field_get:Protocol.BattlePawnDelta.hp)
  return _internal_hp();
}
inline void BattlePawnDelta::_internal_set_hp(int32_t value) {
  
  _impl_.hp_ = value;
}
inline void BattlePawnDelta::set_hp(int32_t value) {
  _internal_set_hp(value);
  // @@protoc_insertion_point(field_set:Protocol.BattlePawnDelta.hp)
}

// int32 armor = 3;
inline void BattlePawnDelta::clear_armor() {
  _impl_.armor_ = 0;
}
inline int32_t BattlePawnDelta::_internal_armor() const {
  return _impl_.armor_;
}
inline int32_t BattlePawnDelta::armor() const {
  // @@protoc_insertion_point(field_get:Protocol.BattlePawnDelta.armor)
  return _internal_armor();
}
inline void BattlePawnDelta::_internal_set_armor(int32_t value) {
  
  _impl_.armor_ = value;
}
inline void BattlePawnDelta::set_armor(int32_t value) {
  _internal_set_armor(value);
  // @@protoc_insertion_point(field_set:Protocol.BattlePawnDelta.armor)
}

// int32 current_ap = 4;
inline void BattlePawnDelta::clear_current_ap() {
  _impl_.current_ap_ = 0;
}
inline int32_t BattlePawnDelta::_internal_current_ap() const {
  return _impl_.current_ap_;
}
inline int32_t BattlePawnDelta::current_ap() const {
  // @@protoc_insertion_point(field_get:Protocol.BattlePawnDelta.current_ap)
  return _internal_current_ap();
}
inline void BattlePawnDelta::_internal_set_current_ap(int32_t value) {
  
  _impl_.current_ap_ = value;
}
inline void BattlePawnDelta::set_current_ap(int32_t value) {
  _internal_set_current_ap(value);
  // @@protoc_insertion_point(field_set:Protocol.BattlePawnDelta.current_ap)
}

// bool can_move = 5;
inline void BattlePawnDelta::clear_can_move() {
  _impl_.can_move_ = false;
}
inline bool BattlePawnDelta::_internal_can_move() const {
  return _impl_.can_move_;
}
inline bool BattlePawnDelta::can_move() const {
  // @@protoc_insertion_point(field_get:Protocol.BattlePawnDelta.can_move)
  return _internal_can_move();
}
inline void BattlePawnDelta::_internal_set_can_move(bool value) {
  
  _impl_.can_move_ = value;
}
inline void BattlePawnDelta::set_can_move(bool value) {
  _internal_set_can_move(value);
  // @@protoc_insertion_point(field_set:Protocol.BattlePawnDelta.can_move)
}

// bool used_sub_action_this_turn = 6;
inline void BattlePawnDelta::clear_used_sub_action_this_turn() {
  _impl_.used_sub_action_this_turn_ = false;
}
inline bool BattlePawnDelta::_internal_used_sub_action_this_turn() const {
  return _impl_.used_sub_action_this_turn_;
}
inline bool BattlePawnDelta::used_sub_action_this_turn() const {
  // @@protoc_insertion_point(field_get:Protocol.BattlePawnDelta.used_sub_action_this_turn)
  return _internal_used_sub_action_this_turn();
}
inline void BattlePawnDelta::_internal_set_used_sub_action_this_turn(bool value) {
  
  _impl_.used_sub_action_this_turn_ = value;
}
inline void BattlePawnDelta::set_used_sub_action_this_turn(bool value) {
  _internal_set_used_sub_action_this_turn(value);
  // @@protoc_insertion_point(field_set:Protocol.BattlePawnDelta.used_sub_action_this_turn)
}

// bool used_ultimate = 7;
inline void BattlePawnDelta::clear_used_ultimate() {
  _impl_.used_ultimate_ = false;
}
inline bool BattlePawnDelta::_internal_used_ultimate() const {
  return _impl_.used_ultimate_;
}
inline bool BattlePawnDelta::used_ultimate() const {
  // @@protoc_insertion_point(field_get:Protocol.BattlePawnDelta.used_ultimate)
  return _internal_used_ultimate();
}
inline void BattlePawnDelta::_internal_set_used_ultimate(bool value) {
  
  _impl_.used_ultimate_ = value;
}
inline void BattlePawnDelta::set_used_ultimate(bool value) {
  _internal_set_used_ultimate(value);
  // @@protoc_insertion_point(field_set:Protocol.BattlePawnDelta.used_ultimate)
}

// -------------------------------------------------------------------

// BattleActionLog

// uint64 attacker_pawn_id = 1;
inline void BattleActionLog::clear_attacker_pawn_id() {
  _impl_.attacker_pawn_id_ = uint64_t{0u};
}
inline uint64_t BattleActionLog::_internal_attacker_pawn_id() const {
  return _impl_.attacker_pawn_id_;
}
inline uint64_t BattleActionLog::attacker_pawn_id() const {
  // @@protoc_insertion_point(field_get:Protocol.BattleActionLog.attacker_pawn_id)
  return _internal_attacker_pawn_id();
}
inline void BattleActionLog::_internal_set_attacker_pawn_id(uint64_t value) {
  
  _impl_.attacker_pawn_id_ = value;
}
inline void BattleActionLog::set_attacker_pawn_id(uint64_t value) {
  _internal_set_attacker_pawn_id(value);
  // @@protoc_insertion_point(field_set:Protocol.BattleActionLog.attacker_pawn_id)
}

// uint64 defender_pawn_id = 2;
inline void BattleActionLog::clear_defender_pawn_id() {
  _impl_.defender_pawn_id_ = uint64_t{0u};
}
inline uint64_t BattleActionLog::_internal_defender_pawn_id() const {
  return _impl_.defender_pawn_id_;
}
inline uint64_t BattleActionLog::defender_pawn_id() const {
  // @@protoc_insertion_point(field_get:Protocol.BattleActionLog.defender_pawn_id)
  return _internal_defender_pawn_id();
}
inline void BattleActionLog::_internal_set_defender_pawn_id(uint64_t value) {
  
  _impl_.defender_pawn_id_ = value;
}
inline void BattleActionLog::set_defender_pawn_id(uint64_t value) {
  _internal_set_defender_pawn_id(value);
  // @@protoc_insertion_point(field_set:Protocol.BattleActionLog.defender_pawn_id)
}

// int32 skill_slot = 3;
inline void BattleActionLog::clear_skill_slot() {
  _impl_.skill_slot_ = 0;
}
inline int32_t BattleActionLog::_internal_skill_slot() const {
  return _impl_.skill_slot_;
}
inline int32_t BattleActionLog::skill_slot() const {
  // @@protoc_insertion_point(field_get:Protocol.BattleActionLog.skill_slot)
  return _internal_skill_slot();
}
inline void BattleActionLog::_internal_set_skill_slot(int32_t value) {
  
  _impl_.skill_slot_ = value;
}
inline void BattleActionLog::set_skill_slot(int32_t value) {
  _internal_set_skill_slot(value);
  // @@protoc_insertion_point(field_set:Protocol.BattleActionLog.skill_slot)
}

// string action_type = 4;
inline void BattleActionLog::clear_action_type() {
  _impl_.action_type_.ClearToEmpty();
}
inline const std::string& BattleActionLog::action_type() const {
  // @@protoc_insertion_point(field_get:Protocol.BattleActionLog.action_type)
  return _internal_action_type();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void BattleActionLog::set_action_type(ArgT0&& arg0, ArgT... args) {
 
 _impl_.action_type_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Protocol.BattleActionLog.action_type)
}
inline std::string* BattleActionLog::mutable_action_type() {
  std::string* _s = _internal_mutable_action_type();
  // @@protoc_insertion_point(field_mutable:Protocol.BattleActionLog.action_type)
  return _s;
}
inline const std::string& BattleActionLog::_internal_action_type() const {
  return _impl_.action_type_.Get();
}
inline void BattleActionLog::_internal_set_action_type(const std::string& value) {
  
  _impl_.action_type_.Set(value, GetArenaForAllocation());
}
inline std::string* BattleActionLog::_internal_mutable_action_type() {
  
  return _impl_.action_type_.Mutable(GetArenaForAllocation());
}
inline std::string* BattleActionLog::release_action_type() {
  // @@protoc_insertion_point(field_release:Protocol.BattleActionLog.action_type)
  return _impl_.action_type_.Release();
}
inline void BattleActionLog::set_allocated_action_type(std::string* action_type) {
  if (action_type != nullptr) {
    
  } else {
    
  }
  _impl_.action_type_.SetAllocated(action_type, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.action_type_.IsDefault()) {
    _impl_.action_type_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Protocol.BattleActionLog.action_type)
}

// int32 damage = 5;
inline void BattleActionLog::clear_damage() {
  _impl_.damage_ = 0;
}
inline int32_t BattleActionLog::_internal_damage() const {
  return _impl_.damage_;
}
inline int32_t BattleActionLog::damage() const {
  // @@protoc_insertion_point(field_get:Protocol.BattleActionLog.damage)
  return _internal_damage();
}
inline void BattleActionLog::_internal_set_damage(int32_t value) {
  
  _impl_.damage_ = value;
}
inline void BattleActionLog::set_damage(int32_t value) {
  _internal_set_damage(value);
  // @@protoc_insertion_point(field_set:Protocol.BattleActionLog.damage)
}

// bool is_critical = 6;
inline void BattleActionLog::clear_is_critical() {
  _impl_.is_critical_ = false;
}
inline bool BattleActionLog::_internal_is_critical() const {
  return _impl_.is_critical_;
}
inline bool BattleActionLog::is_critical() const {
  // @@protoc_insertion_point(field_get:Protocol.BattleActionLog.is_critical)
  return _internal_is_critical();
}
inline void BattleActionLog::_internal_set_is_critical(bool value) {
  
  _impl_.is_critical_ = value;
}
inline void BattleActionLog::set_is_critical(bool value) {
  _internal_set_is_critical(value);
  // @@protoc_insertion_point(field_set:Protocol.BattleActionLog.is_critical)
}

// bool is_evaded = 7;
inline void BattleActionLog::clear_is_evaded() {
  _impl_.is_evaded_ = false;
}
inline bool BattleActionLog::_internal_is_evaded() const {
  return _impl_.is_evaded_;
}
inline bool BattleActionLog::is_evaded() const {
  // @@protoc_insertion_point(field_get:Protocol.BattleActionLog.is_evaded)
  return _internal_is_evaded();
}
inline void BattleActionLog::_internal_set_is_evaded(bool value) {
  
  _impl_.is_evaded_ = value;
}
inline void BattleActionLog::set_is_evaded(bool value) {
  _internal_set_is_evaded(value);
  // @@protoc_insertion_point(field_set:Protocol.BattleActionLog.is_evaded)
}

// bool is_guarded = 8;
inline void BattleActionLog::clear_is_guarded() {
  _impl_.is_guarded_ = false;
}
inline bool BattleActionLog::_internal_is_guarded() const {
  return _impl_.is_guarded_;
}
inline bool BattleActionLog::is_guarded() const {
  // @@protoc_insertion_point(field_get:Protocol.BattleActionLog.is_guarded)
  return _internal_is_guarded();
}
inline void BattleActionLog::_internal_set_is_guarded(bool value) {
  
  _impl_.is_guarded_ = value;
}
inline void BattleActionLog::set_is_guarded(bool value) {
  _internal_set_is_guarded(value);
  // @@protoc_insertion_point(field_set:Protocol.BattleActionLog.is_guarded)
}

// bool is_perfect_guarded = 9;
inline void BattleActionLog::clear_is_perfect_guarded() {
  _impl_.is_perfect_guarded_ = false;
}
inline bool BattleActionLog::_internal_is_perfect_guarded() const {
  return _impl_.is_perfect_guarded_;
}
inline bool BattleActionLog::is_perfect_guarded() const {
  // @@protoc_insertion_point(field_get:Protocol.BattleActionLog.is_perfect_guarded)
  return _internal_is_perfect_guarded();
}
inline void BattleActionLog::_internal_set_is_perfect_guarded(bool value) {
  
  _impl_.is_perfect_guarded_ = value;
}
inline void BattleActionLog::set_is_perfect_guarded(bool value) {
  _internal_set_is_perfect_guarded(value);
  // @@protoc_insertion_point(field_set:Protocol.BattleActionLog.is_perfect_guarded)
}

// bool is_counter = 10;
inline void BattleActionLog::clear_is_counter() {
  _impl_.is_counter_ = false;
}
inline bool BattleActionLog::_internal_is_counter() const {
  return _impl_.is_counter_;
}
inline bool BattleActionLog::is_counter() const {
  // @@protoc_insertion_point(field_get:Protocol.BattleActionLog.is_counter)
  return _internal_is_counter();
}
inline void BattleActionLog::_internal_set_is_counter(bool value) {
  
  _impl_.is_counter_ = value;
}
inline void BattleActionLog::set_is_counter(bool value) {
  _internal_set_is_counter(value);
  // @@protoc_insertion_point(field_set:Protocol.BattleActionLog.is_counter)
}

// int32 hp_after = 11;
inline void BattleActionLog::clear_hp_after() {
  _impl_.hp_after_ = 0;
}
inline int32_t BattleActionLog::_internal_hp_after() const {
  return _impl_.hp_after_;
}
inline int32_t BattleActionLog::hp_after() const {
  // @@protoc_insertion_point(field_get:Protocol.BattleActionLog.hp_after)
  return _internal_hp_after();
}
inline void BattleActionLog::_internal_set_hp_after(int32_t value) {
  
  _impl_.hp_after_ = value;
}
inline void BattleActionLog::set_hp_after(int32_t value) {
  _internal_set_hp_after(value);
  // @@protoc_insertion_point(field_set:Protocol.BattleActionLog.hp_after)
}

// int32 armor_after = 12;
inline void BattleActionLog::clear_armor_after() {
  _impl_.armor_after_ = 0;
}
inline int32_t BattleActionLog::_internal_armor_after() const {
  return _impl_.armor_after_;
}
inline int32_t BattleActionLog::armor_after() const {
  // @@protoc_insertion_point(field_get:Protocol.BattleActionLog.armor_after)
  return _internal_armor_after();
}
inline void BattleActionLog::_internal_set_armor_after(int32_t value) {
  
  _impl_.armor_after_ = value;
}
inline void BattleActionLog::set_armor_after(int32_t value) {
  _internal_set_armor_after(value);
  // @@protoc_insertion_point(field_set:Protocol.BattleActionLog.armor_after)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace Protocol

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_Struct_2eproto
