// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Enum.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_Enum_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_Enum_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_Enum_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_Enum_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_Enum_2eproto;
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE
namespace Protocol {

enum ObjectType : int {
  OBJECT_TYPE_NONE = 0,
  OBJECT_TYPE_CREATURE = 1,
  OBJECT_TYPE_PROJECTILE = 2,
  OBJECT_TYPE_ENV = 3,
  ObjectType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  ObjectType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool ObjectType_IsValid(int value);
constexpr ObjectType ObjectType_MIN = OBJECT_TYPE_NONE;
constexpr ObjectType ObjectType_MAX = OBJECT_TYPE_ENV;
constexpr int ObjectType_ARRAYSIZE = ObjectType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ObjectType_descriptor();
template<typename T>
inline const std::string& ObjectType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, ObjectType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function ObjectType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    ObjectType_descriptor(), enum_t_value);
}
inline bool ObjectType_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, ObjectType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<ObjectType>(
    ObjectType_descriptor(), name, value);
}
enum CreatureType : int {
  CREATURE_TYPE_NONE = 0,
  CREATURE_TYPE_PLAYER = 1,
  CREATURE_TYPE_MONSTER = 2,
  CREATURE_TYPE_NPC = 3,
  CreatureType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  CreatureType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool CreatureType_IsValid(int value);
constexpr CreatureType CreatureType_MIN = CREATURE_TYPE_NONE;
constexpr CreatureType CreatureType_MAX = CREATURE_TYPE_NPC;
constexpr int CreatureType_ARRAYSIZE = CreatureType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* CreatureType_descriptor();
template<typename T>
inline const std::string& CreatureType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, CreatureType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function CreatureType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    CreatureType_descriptor(), enum_t_value);
}
inline bool CreatureType_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, CreatureType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<CreatureType>(
    CreatureType_descriptor(), name, value);
}
enum PawnClass : int {
  PAWN_CLASS_NONE = 0,
  PAWN_CLASS_SUEN_AXE_SWORD = 1,
  PAWN_CLASS_SUEN_PARVIS = 2,
  PAWN_CLASS_BEIGE_FIRE = 3,
  PAWN_CLASS_BEIGE_ICE = 4,
  PAWN_CLASS_ZILLIAN_LONGBOW = 5,
  PAWN_CLASS_ZILLIAN_MACE = 6,
  PAWN_CLASS_ALEN_SPEAR = 7,
  PAWN_CLASS_ALEN_SWORD_SHIELD = 8,
  PAWN_CLASS_SERA_NECROMANCER = 9,
  PAWN_CLASS_SERA_WARLOCK = 10,
  PAWN_CLASS_DARKHAND_SWORD = 101,
  PawnClass_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  PawnClass_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool PawnClass_IsValid(int value);
constexpr PawnClass PawnClass_MIN = PAWN_CLASS_NONE;
constexpr PawnClass PawnClass_MAX = PAWN_CLASS_DARKHAND_SWORD;
constexpr int PawnClass_ARRAYSIZE = PawnClass_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* PawnClass_descriptor();
template<typename T>
inline const std::string& PawnClass_Name(T enum_t_value) {
  static_assert(::std::is_same<T, PawnClass>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function PawnClass_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    PawnClass_descriptor(), enum_t_value);
}
inline bool PawnClass_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, PawnClass* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<PawnClass>(
    PawnClass_descriptor(), name, value);
}
enum BattleMoveResult : int {
  BATTLE_MOVE_RESULT_NONE = 0,
  BATTLE_MOVE_RESULT_OK = 1,
  BATTLE_MOVE_RESULT_NOT_YOUR_TURN = 2,
  BATTLE_MOVE_RESULT_NOT_OWNER = 3,
  BATTLE_MOVE_RESULT_NOT_WALKABLE = 4,
  BATTLE_MOVE_RESULT_OUT_OF_RANGE = 5,
  BATTLE_MOVE_RESULT_OCCUPIED = 6,
  BATTLE_MOVE_RESULT_INVALID_BATTLE = 7,
  BATTLE_MOVE_RESULT_INVALID_PAWN = 8,
  BattleMoveResult_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  BattleMoveResult_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool BattleMoveResult_IsValid(int value);
constexpr BattleMoveResult BattleMoveResult_MIN = BATTLE_MOVE_RESULT_NONE;
constexpr BattleMoveResult BattleMoveResult_MAX = BATTLE_MOVE_RESULT_INVALID_PAWN;
constexpr int BattleMoveResult_ARRAYSIZE = BattleMoveResult_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* BattleMoveResult_descriptor();
template<typename T>
inline const std::string& BattleMoveResult_Name(T enum_t_value) {
  static_assert(::std::is_same<T, BattleMoveResult>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function BattleMoveResult_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    BattleMoveResult_descriptor(), enum_t_value);
}
inline bool BattleMoveResult_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, BattleMoveResult* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<BattleMoveResult>(
    BattleMoveResult_descriptor(), name, value);
}
// ===================================================================


// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace Protocol

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::Protocol::ObjectType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Protocol::ObjectType>() {
  return ::Protocol::ObjectType_descriptor();
}
template <> struct is_proto_enum< ::Protocol::CreatureType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Protocol::CreatureType>() {
  return ::Protocol::CreatureType_descriptor();
}
template <> struct is_proto_enum< ::Protocol::PawnClass> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Protocol::PawnClass>() {
  return ::Protocol::PawnClass_descriptor();
}
template <> struct is_proto_enum< ::Protocol::BattleMoveResult> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Protocol::BattleMoveResult>() {
  return ::Protocol::BattleMoveResult_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_Enum_2eproto
